In [1]:
import numpy as np

###Takrorlanuvchi massivlar

In [6]:
arry1 = np.arange(1,10)

In [7]:
arry1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
for n in arry1:
  pass
  #print(n*2)

###2D massivlarni takrorlash
##2 o'lchovli massivda u barcha qatorlardan o'tadi.

In [11]:
arry2 = np.array([[1, 2, 3], [4, 5, 6]])
arry2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
for n in arry2:
  print(n*2)

[2 4 6]
[ 8 10 12]


###2-D massivning har bir skaler elementida takrorlang

In [ ]:
for n in arry2:
  for x in n:
    print(x)


In [ ]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


In [ ]:



arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

###nditer() yordamida massivlarni takrorlash

In [19]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
for n in np.nditer(arr):
  print(n)

###Har xil ma'lumotlar turlari bilan takrorlanuvchi massiv
##Biz op_dtypesiteratsiya paytida elementlarning ma'lumotlar turini o'zgartirish uchun argumentdan foydalanishimiz va unga kutilgan ma'lumotlar turini berishimiz mumkin.
####NumPy o'z joyida (element massivda joylashgan) elementning ma'lumotlar turini o'zgartirmaydi, shuning uchun bu amalni bajarish uchun boshqa joy kerak, bu qo'shimcha joy bufer deb ataladi va uni yoqish uchun nditer()biz o'tkazamiz flags=['buffered'].

In [21]:
import numpy as np

arr3 = np.array([1, 2, 3])

for x in np.nditer(arr3, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [28]:
arr.ndim

3

In [25]:
arry3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arry3[:, ::2]):
  print(x)

1
3
5
7


###Ba'zan biz iteratsiya paytida elementning mos indeksini talab qilamiz, bu ndenumerate() usuldan foydalanish holatlari uchun foydalanish mumkin.

In [27]:
for x,n in np.ndenumerate(arry3): # arry mos index bilan chiqarish 
  print(x,n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [29]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#NumPy Joining Array
##NumPy qo'shilish massivi

####Birlashma ikki yoki undan ortiq massivlar tarkibini bitta massivga joylashtirishni bildiradi.

####SQL-da biz jadvallarni kalit asosida birlashtiramiz, NumPy-da esa massivlarni o'qlar bo'yicha birlashtiramiz.

####Biz concatenate()funktsiyaga qo'shmoqchi bo'lgan massivlar ketma-ketligini eksa bilan birga o'tkazamiz. Agar o'q aniq o'tkazilmasa, u 0 sifatida qabul qilinadi.

In [36]:
arry4 = np.array([1,2,3])
arry5 = np.array([4,5,6])
arr = np.concatenate((arry4,arry5))  # bu ikkita massivni birlashtirish 

In [35]:
arr

array([1, 2, 3, 4, 5, 6])

In [39]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [41]:
arr2

array([[5, 6],
       [7, 8]])

In [42]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [43]:
arry1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#Stack funksiyalari yordamida massivlarni birlashtirish

In [45]:
print(arr1)
print(" ")
print(arr2)

[[1 2]
 [3 4]]
 
[[5 6]
 [7 8]]


In [46]:
list = np.stack((arr1,arr2), axis=1)

In [47]:
list

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [48]:
list.ndim

3

In [49]:
list = np.stack((arr1,arr2))

In [ ]:
list


#Qatorlar bo'ylab yig'ish
### hstack() qatorlar bo'ylab stack qilish.

In [55]:
print(arr1)
print(arr2)
list = np.hstack((arr1,arr2))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [53]:
list

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#Ustunlar bo'ylab stacking
###vstack()  ustunlar bo'ylab stack qilish.

In [56]:
list = np.vstack((arr1,arr2))
print(list)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [57]:
list1 = np.dstack((arr1,arr2))  # dstack() balandlik bo'ylab stack qilish, bu chuqurlik bilan bir xil.
print(list1)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
