In [ ]:
import numpy as np

In [ ]:
# data
names = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [ ]:
np.unique(names) # unique
np.unique(names) # names dagi takrorlanmas elementlarni qaytaradi (takrorlansa ham faqat bittasini qabul qiladi)

array(['Abdurahmon', 'Hasan', 'Sarvar', 'Temur'], dtype='<U10')

In [ ]:
set(names) # bu bizlarga unique() funksiyasi bilan yani takrorlanmas funksiyasini beradi

{'Abdurahmon', 'Hasan', 'Sarvar', 'Temur'}

In [ ]:
arr = np.array([3,1,5])

In [ ]:
np.in1d(ints,arr)   # bu 1 arr mizdagi elemtlar 2 arrmizdagi elemtlarni ichida bormi yoqmi aniqlaydi 

array([ True,  True,  True, False, False,  True,  True, False, False])

### `setdiff1d` usuli haqida

In [ ]:
#data
names1 = np.array(['Jasur', 'Abdurahmon', 'Hasan',  'Muhammad', 'Sarvar', 'Temur'])
names2 = np.array(['Sarvar', 'Abdurahmon', 'Hasan',  'Temur', 'Sarvar', 'Temur'])

In [ ]:
np.setdiff1d(names1, names)

array(['Jasur', 'Muhammad'], dtype='<U10')

#Numpy file lar bilan ishlash 

In [ ]:
arry = np.arange(10)

In [ ]:
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.save('data',arry)

In [ ]:
arr1 = np.load('data.npy')

In [ ]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = np.arange(20)

In [ ]:
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.savez('data1.npy',a=arry,b=arr2)

In [ ]:
arrays = np.load('data1.npy.npz')

In [ ]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# chiziqli Algebra usuli 

In [8]:
import numpy as np
x = np.array([[1.,2.,3.],[1.,2.,3.]])