In [2]:
import numpy as np

In [3]:
arr1  = np.arange(1,7)

In [4]:
arr1

array([1, 2, 3, 4, 5, 6])

#NumPy massivlarini ajratish

In [6]:
 arr = np.array_split(arr1,3) # array_split() funksiyasi bu massivlarga bo'lish uchun ishlatiladi 

In [7]:
arr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [8]:
arr = np.array_split(arr1,4)
arr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

#2-D massivlarni ajratish

In [10]:
arr2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [11]:
arr  =np.array_split(arr2,3)

In [12]:
arr

[array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]), array([[ 9, 10],
        [11, 12]])]

#NumPy qidiruv massivlari
###Massivni qidirish uchun where() usuldan foydalaning.

In [13]:
arr1

array([1, 2, 3, 4, 5, 6])