### Numpy 1 2 3 o'lchamli massiv yaratish 


In [1]:
import numpy as np

In [5]:
arry1 = np.array([1,2,3,4,5]) # bu bir o'lchamli massiv
arry1

array([1, 2, 3, 4, 5])

In [43]:
arry2 = np.array([[1, 2, 3], [4, 5, 6]])  # bu ikki o'lchamli massiv 
arry2  

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arry3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # uch o'lchamli massiv yaratish 
arry3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [9]:
arry3.ndim

3

In [10]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

### Array indexlash 

In [11]:
arr.ndim

5

In [13]:
arry4 = np.arange(6)

In [14]:
arry4

array([0, 1, 2, 3, 4, 5])

In [16]:
arry4[3] # bu bir o'lchami massivni indexlash 

3

In [18]:
arry5 = np.array([[1, 2, 3], [4, 5, 6]]) 
arry5

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
print(arry5[1,1])  # 2D massivni indexlash 
print(arry5[0,0])  # 2D massivni indexlash 

5
1


In [21]:
arry6 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arry6

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
arry6[0] # 3D massivni indexlash uchun biz 2D massivga o'tqizib olamiz

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arry6[0][1,1] # 3D massivni indexlash 

5

In [24]:
arry6[0,1,1] # 3D massivni indexlash 

5

###NumPy Array Slicing

In [25]:
arry7 = np.arange(10)

In [26]:
arry7


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arry7[4:7]

array([4, 5, 6])

### Numpy ma'lumotlar turlari
##i - integer
##b - boolean
##u - unsigned integer
##f - float
##c - complex float
##m - timedelta
##M - datetime
##O - object
##S - string
##U - unicode string
##V - fixed chunk of memory for other type ( void ) 

In [29]:
print(arry7.dtype) 

int64


In [30]:
arry8 = np.array(['olma', 'anor','nok', 'shaftoli'])

In [32]:
arry8.dtype  # Qaysi ma'lumot turuga tegishli ekanini bilish 

dtype('<U8')

In [34]:
arry9 = np.array([1, 2, 3, 4], dtype='S') # Bu type o'zimiz berishga misol

In [35]:
arry9

array([b'1', b'2', b'3', b'4'], dtype='|S1')

###NumPy Array Copy vs View 
##NumPy massividan nusxa ko'chirish va ko'rish

In [47]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [48]:
arry10  =arry1.copy()

In [49]:
arry10

array([1, 2, 3, 4, 5])

In [50]:
arry10[0]=0

In [51]:
arry10

array([0, 2, 3, 4, 5])

###NumPy Array Shape
##NumPy massivlari shape har bir indeks mos keladigan elementlar soniga ega bo'lgan kortejni qaytaradigan atributga ega.

In [52]:
arry10.shape

(5,)

###NumPy Array Reshaping

In [53]:
arry11 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arry11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
arry11.reshape(4,3) # Shaklni 1-D dan 2-D ga oʻzgartiring

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
arry11.reshape(3,4) # Shaklni 1-D dan 2-D ga oʻzgartiring

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
arry12 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # Shaklni 1-D dan 3-D ga oʻzgartiring
arry12.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### reshape Har qanday shaklga o'zgartirishimiz mumkin

In [64]:
arry13 = np.array([[1, 2, 3], [4, 5, 6]]) 
arry13.reshape(-1)                           # 2D massivni 1D massivga aylantierish

array([1, 2, 3, 4, 5, 6])